# Generated by Django 5.2.7 on 2025-11-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=1000)),
                ("logo", models.CharField(blank=True, max_length=1000)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("subcategories", models.JSONField(blank=True, default=list)),
                ("pricing", models.CharField(blank=True, max_length=100)),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("source_link", models.URLField(db_column="url", max_length=500)),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_favicon",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DR", "Draft"),
                            ("PR", "Pending Review"),
                            ("PB", "Published"),
                            ("ER", "Error"),
                        ],
                        default="DR",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("industry_tags", models.JSONField(default=list)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("vendors", models.JSONField(blank=True, default=list)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.newsarticle",
                    ),
                ),
            ],
        ),
    ]
